# This is a basic workflow to help you get started with Actions

name: Apache-WEB-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Copying index file to /var/www/html
        run: |
          sudo cp /root/githubactions/index.html /var/www/html/
          sudo service restart httpd
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    

